# Generated by Django 4.2.11 on 2024-07-18 22:38

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_alter_article_table_alter_articleview_table_and_more"),
    ]

    operations = [
        migrations.RunSQL(sql="CREATE EXTENSION pg_bigm;", reverse_sql=""),
        migrations.AddIndex(
            model_name="article",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="article_title_gin_index", opclasses=["gin_bigm_ops"]
            ),
        ),
    ]
