# Generated by Django 4.2.11 on 2024-08-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_article_article_title_gin_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="thumbnail",
            field=models.ImageField(
                default=None, null=True, upload_to="article_thumbnails", verbose_name="article thumbnail"
            ),
        ),
    ]
