# Generated by Django 4.2.11 on 2024-08-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_article_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="thumbnail",
            new_name="thumbnail_url",
        ),
    ]
