#!/bin/bash

# error to exit process
set -o errexit

# pipeline ar executed successfully
set -o pipefail

# sciprt to exit unitialized variable is usesd
set -o nounset

echo "==> Django setup, executing: makemigrations "
python3 booklog/manage.py makemigrations
echo "==> Django setup, executing: migrate pro"
python3 booklog/manage.py migrate --no-input
echo "==> collections setup, executing: collectstatic"
python booklog/manage.py collectstatic --no-input
echo "==> runserver by gunicorn '0:8000' port bind"
cd booklog
exec gunicorn --bind 0:8000 config.wsgi:application
