services:
  postgres:
    build:
      context: .
      dockerfile: docker/dev/database/Dockerfile
    volumes:
      - stage_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.dev/.database
    ports:
      - "5433:5432"
    networks:
      - api-server

  api:
    container_name: api-server
    build:
      context: .
      dockerfile: docker/dev/django/Dockerfile
    command: /start
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - '8000:8000'
    environment:
      - DJANGO_SETTINGS_MODULE=config.django.dev
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.database
    restart: unless-stopped
    networks:
      - api-server

  nginx:
    container_name: nginx
    restart: always
    depends_on:
        - api
    volumes:
        - static_volume:/app/staticfiles
        - media_volume:/app/mediafiles
    build:
        context: ./docker/dev/nginx
        dockerfile: Dockerfile
    ports:
        - "80:80"
    networks:
        - api-server

networks:
    api-server:
        driver: bridge

volumes:
    static_volume:
    media_volume:
    stage_postgres_data:
