# Generated by Django 4.2.11 on 2024-06-23 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="comment",
            table="comments",
        ),
    ]
