# Generated by Django 4.2.11 on 2024-08-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_books_isbn_ce4a1a_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="thumbnail_url",
            field=models.ImageField(
                default="book_thumbnails/default_book.png", upload_to="book_thumbnails", verbose_name="Thumbnail"
            ),
        ),
    ]
